.PHONY: run-dev run-uat run-prod run-prod-release build-apk-prod build-aab-prod build-ios-prod

run-dev:
	./tool/run_env.sh dev run

run-uat:
	./tool/run_env.sh uat run

run-prod:
	./tool/run_env.sh prod run

run-prod-release:
	./tool/run_env.sh prod run-release

build-apk-prod:
	./tool/run_env.sh prod build-apk

build-aab-prod:
	./tool/run_env.sh prod build-appbundle

build-ios-prod:
	./tool/run_env.sh prod build-ios

