name: bvc_services
description: Khách sạn / ăn uống / combo (feature module)
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.2
  flutter_riverpod: ^3.3.1
  flutter_modular: ^6.4.1
  bvc_network:
    path: ../bvc_network
  bvc_common:
    path: ../bvc_common
  bvc_ui:
    path: ../bvc_ui
